export const GOALS = [
    {
      id: 1,
      title: "Learn Spring Boot",
      objective: "Become proficient in Spring Boot development.",
      category: "Learning",
      priority: "High",
      deadline: "30 Jul 2026",
      progress: 60,
      status: "In Progress",
    },
    {
      id: 2,
      title: "Build SaaS Project",
      objective: "Complete the SaaS project before final review.",
      category: "Project",
      priority: "High",
      deadline: "15 Aug 2026",
      progress: 40,
      status: "In Progress",
    },
    {
      id: 3,
      title: "Complete React Course",
      objective: "Finish React and Tailwind CSS course.",
      category: "Learning",
      priority: "Medium",
      deadline: "10 Aug 2026",
      progress: 80,
      status: "In Progress",
    },
    {
      id: 4,
      title: "Practice DSA",
      objective: "Solve 50 coding questions.",
      category: "Career",
      priority: "Low",
      deadline: "31 Aug 2026",
      progress: 20,
      status: "Not Started",
    },
  ];